export enum ControllerActions {
    NEW = 'NEW-PLAYER',
    GET_AVATARS_IN_USE = 'GET-AVATARS-IN-USE',
    SET_AVATAR = 'SET-AVATAR',
    UPDATE_AVATAR_SELECTOR = 'UPDATE-AVATAR-SELECTOR',
    ASSIGNED_SUCCESSFUL = 'PLAYER-ASSIGNED-SUCCESSFUL',
    GAME_ALREADY_STARTED = 'GAME-ALREADY-STARTED',
    GAME_FULL = 'GAME-FULL',
    GAME_NOT_AVAILABLE = 'GAME-NOT-AVAILABLE',
    START_GAME = 'START-GAME',
    START_GAME = 'START-GAME',
    UPDATE_POSITION = 'UPDATE-POSITION',
    UPDATE_TIMER = 'UPDATE-TIMER',
    SHIELD_STATE = 'SHIELD-STATE',
    UPDATE_SCORE = 'UPDATE-SCORE',
    FIRE_STATE = 'FIRE-STATE'
}