export enum GameActions {
    NEW = 'NEW-GAME',
    START_TIMER = 'START-TIMER',
    PLAYER_DISCONNECTED = 'PLAYER-DISCONNECTED',
    ASSIGNED_SUCCESSFUL = 'GAME-ASSIGNED-SUCCESSFUL',
    UPDATE_PLAYERS_STATE = 'UPDATE_PLAYERS-STATE',
    ALL_PLAYERS = 'GET-ALL-PLAYERS',
    START_GAME = 'START-GAME',
    UPDATE_POSITION = 'UPDATE-POSITION',
    UPDATE_TIMER = 'UPDATE-TIMER',
    SHIELD_STATE = 'SHIELD-STATE',
    UPDATE_SCORE = 'UPDATE-SCORE',
    FIRE_STATE = 'FIRE-STATE'
}